insert into route(id, name, length, price, description) values (1, 'Высокие Татры(Польша)', '~50km', '$150',
 'Наш маршрут по дням:
<ul><li>День 1. Краков-Закопане-Мурованец<p>
Встречаемся ранним утром на авто вокзале в Кракове, знакомимся, распределяем продукты и садимся в рейсовый автобус, который довезет нас к самому известному горнолыжному курорту Польши – к Закопане. Сразуже после прибытия, мы отправляемся на точку старта нашего маршрута и идем себе сначала по лесу, через перевал и спустя 2 часа выходим в долину - Hala Gasienicowa. Здесь, рядом с туристическим приютом Мурованец (схрониско), мы сделаем привал на обед. Далее возможны два варианта прохождения маршрута, если есть места для ночевки  – мы забрасываем вещи и отправляемся на вершину Косчелец (2155 м), второй вариант – осуществляем переход в долину Пяти Ставов для ночевки там.</li>
</p>
<li>День 2. Путь Орла<p>
Сегодня нас ждет экстримальный участок маршрута - Путь Орла, там уж точно каждый получит свою порцию адренаина. Орала Перч  несомненно, самая сложная трекинговая трасса в польских Татрах. Это скалистый гребень, на котором сооружены искуственные перила (цепи), металлические скобы и лестицы, для безопасного прохождения по маршруту. После сложного и насыщенного дня спускаемся в долину Пяти Ставов, а по дороге делаем остоновку у найвысшемго водопада Виелка Сиклава. Ужинаем и ночуем в туристическом приюте.</li>
</p>
<li>День 3. Шпигласовый Верх и переход к Морскому Оку<p>
На сегодня план такой: завтракаем, прогуливаемся в окрестностях долины Пяти Озер, делаем красивые фотки, наслаждаемся живописными видами и компанией. А после собираем вещи и отправляемся к самому культому месту в Татрах - Морскому Оку. Наш путь лежит через горный перевел на высоте 2110 м. С этого места до вершины Шпигласовый Верх (2172 м) остается каких то 15 минут. Со Шпигласова перевала открывается незабываемый вид, он отделяет друг от друга окрестности красивейшей долины Пяти Озер и Морского Ока. Вдоволь насладившись панорамой спускаемся и размещаемся для ночевки в схрониску над Морским Окем.</li>
</p>
<li>День 4. Восхождение на Рысы.<p>
На сегодня у нас одна цель - подняться на высочайший пик в Польше - Рысы (2499 м). На самом деле у Рысы три вершины, самая высокая - 2503 м, находиться посностью по Словацкой стороне, а вторая - высотой 2499 м лежит на главном хребте Татр, через который проходит Польско-Словацкая граница. Путь предстоит долгим так, что ранний подъем, завтрак и отправляемся на трек.
Трудно сравнивать всю красоту видов с другими местами в Татрах. А стоя на вершине наш взгляд охватывает более 100 пиков, и это самая обширная панорама. Спускаемся в схрониско, ужинаем, отмечаем удачно пройденный трек).</li>
</p>
<li>День 5. <p>Ну вот, план максимум выполнен. Можем с чистой совестью и довольной душой отправляться домой. Спуск по долине очень комфортный - шагаем асвальтированной дорогой к паркингу, где садимся на маршрутку до Закопанего. Там я с вами прощаюсь до следующего раза)) Ну а вам рекомендую: прогуляться по зеленым улицам, отведать горальскую кухню, посетить месный рынок и накупить сувениров.</p></li></ul>');
-- insert into route(id, name, length, price, description) values (2, 'Высокие Татры(Словакия)', '~20km',  '$150','The trail starts at East Entrance trailhead and climbs 1,000 feet onto the rim with views into Jolley Gulch and the east side slickrock areas. The first stretch of trail offers sweeping views of the slickrock areas on the east side before walking through the high ponderosa forest. After you traverse the rim the views of the Echo Canyon basin open up as you near the East Rim. After hiking over the rim of the canyon you sharply descend 2,300 feet down to the floor of Zion Canyon ending at Weeping Rock, passing through Echo Canyon and down the Observation Point Trail. This area has no established campsites but does require a permit.');
-- insert into route(id, name, length, price, description) values (3, 'Словацкий Рай', '~30km',  '$150','The trail starts at East Entrance trailhead and climbs 1,000 feet onto the rim with views into Jolley Gulch and the east side slickrock areas. The first stretch of trail offers sweeping views of the slickrock areas on the east side before walking through the high ponderosa forest. After you traverse the rim the views of the Echo Canyon basin open up as you near the East Rim. After hiking over the rim of the canyon you sharply descend 2,300 feet down to the floor of Zion Canyon ending at Weeping Rock, passing through Echo Canyon and down the Observation Point Trail. This area has no established campsites but does require a permit.');
-- insert into route(id, name, length, price, description) values (4, 'short route 2', '20km',  '$150','The trail starts at East Entrance trailhead and climbs 1,000 feet onto the rim with views into Jolley Gulch and the east side slickrock areas. The first stretch of trail offers sweeping views of the slickrock areas on the east side before walking through the high ponderosa forest. After you traverse the rim the views of the Echo Canyon basin open up as you near the East Rim. After hiking over the rim of the canyon you sharply descend 2,300 feet down to the floor of Zion Canyon ending at Weeping Rock, passing through Echo Canyon and down the Observation Point Trail. This area has no established campsites but does require a permit.');
-- insert into route(id, name, length, price, description) values (5, 'medium route 2', '30km', '$150', 'The trail starts at East Entrance trailhead and climbs 1,000 feet onto the rim with views into Jolley Gulch and the east side slickrock areas. The first stretch of trail offers sweeping views of the slickrock areas on the east side before walking through the high ponderosa forest. After you traverse the rim the views of the Echo Canyon basin open up as you near the East Rim. After hiking over the rim of the canyon you sharply descend 2,300 feet down to the floor of Zion Canyon ending at Weeping Rock, passing through Echo Canyon and down the Observation Point Trail. This area has no established campsites but does require a permit.');
-- insert into route(id, name, length, price, description) values (6, 'short route 3', '20km',  '$150','The trail starts at East Entrance trailhead and climbs 1,000 feet onto the rim with views into Jolley Gulch and the east side slickrock areas. The first stretch of trail offers sweeping views of the slickrock areas on the east side before walking through the high ponderosa forest. After you traverse the rim the views of the Echo Canyon basin open up as you near the East Rim. After hiking over the rim of the canyon you sharply descend 2,300 feet down to the floor of Zion Canyon ending at Weeping Rock, passing through Echo Canyon and down the Observation Point Trail. This area has no established campsites but does require a permit.');
insert into guide(id, info, name) values (1, 'Deus Ex', 'Лилия Сус');
-- insert into guide(id, info, name) values (2, 'Deus Ex', 'Johnny Walker');
insert into route_time_slot(id, guide_id, route_id, available_date, end_date) values (1, 1, 1, PARSEDATETIME ('31-05-18 11:34:24','dd-MM-yy hh:mm:ss'), PARSEDATETIME ('31-06-18 11:34:24','dd-MM-yy hh:mm:ss'));
-- insert into route_time_slot(id, guide_id, route_id, available_date, end_date) values (2, 1, 2,  PARSEDATETIME ('28-05-18 11:34:24','dd-MM-yy hh:mm:ss'), PARSEDATETIME ('31-06-18 11:34:24','dd-MM-yy hh:mm:ss'));
-- insert into route_time_slot(id, guide_id, route_id, available_date, end_date) values (3, 1, 3,  PARSEDATETIME ('28-05-18 11:34:24','dd-MM-yy hh:mm:ss'), PARSEDATETIME ('31-06-18 11:34:24','dd-MM-yy hh:mm:ss'));